### ISSUE TITLE
Basic Questions

### ISSUE THREAD

**Issue by TillThomas** [AndreasFischer1985/diga-api#2]
Hi, I want to access the DiGA API, but I'm unsure if its puplic or how I can make some requests.
Could you ellaborate a little?

**Comment by AndreasFischer1985** [comment]
Dear TillThomas,

thanks for your comment. It seems the DiGA API has been updated to v2, so I updated the documentation accordingly.
You should now be able to access the information of the ["DiGA-Verzeichnis"](https://diga.bfarm.de/de/verzeichnis) by following the documentation. 

Best regards

Andreas
