### ISSUE TITLE
Deployment Fails

### ISSUE THREAD

**Issue by wirthual** [AndreasFischer1985/diga-api#3]
For running the deployment to pypi:
```
Pypi Token: 
TestPypi Token: 
```

Need to be set. In the BundesAPI fork they are empty, thats why the upload fails. Looks like an ownership issue to me, since its forked.

keep it up :)

Best,
wirthual

**Comment by AndreasFischer1985** [comment]
Thanks for your tips. Turns out I had to rename secrets.PYPI_API_TOKEN to secrets.PYPI_PRODUCTION and secrets.TEST_PYPI_API_TOKEN to secrets.PYPI_TEST
